#!/usr/bin/env zsh

LASTPASS_LOGIN="karvus@gmail.com"
LASTPASS_RSA_ID="2551172036"
LASTPASS_RSA_PUB_ID="2551170726"

# try to figure out which distro we're on
determine_distro() {
    if [ -f /etc/arch-release ] ; then
        distro=arch
    else if [ -f  /etc/system-release ] && grep "CentOS Stream release 8" /etc/system-release &> /dev/null ; then
             distro=centos_stream_8
         else
             distro=unknown
         fi
    fi
    info "Determined distro: ${distro}"
}

# set_distro_vars <distro>
set_distro_vars() {
    case "$1" in
       arch)
         install_command="sudo pacman -S"
         query_command="pacman -Q"
         fish_package="fish"
         ;;
       centos8)
           install_command="sudo dnf install"
           query_command="dnf list installed"
           fish_package="fish"
           ;;
       unknown)
           info "Unknown distro, will not be able to install packages"
           ;;
       *)
           error "Distro has been determined, but variables for it not defined"
    esac
}

# info <message>
info() {
    echo DOC: $*
}

# error <message>
error() {
    echo "DOC-ERR: $*"
    exit 1
}

is_ssh_keys_installed() {
    if [ -d ~/.ssh ]  && [ -f ~/.ssh/id_rsa ] && [ -f ~/.ssh/id_rsa.pub ] ; then
        return 0
    else
        return 1
 fi
}

is_fish_installed() {
    command -v fish &> /dev/null
}

install_fish() {

}

install_lastpass() {
    info "Trying to install lastpass"
    case "${distro}" in
        arch)
            sudo pacman -S lastpass-cli
            return $?
            ;;
        *)
            echo "Don't know how to install lastpass-cli for distro ${distro}"
            return 1
            ;;
    esac
}

extract_ssh_keys() {
    if ! [ -d ~/.ssh ] ; then
        info "~/.ssh missing, creating and chmoding"
        mkdir ~/.ssh
        chmod 700 ~/.ssh
    fi
    if ! lpass info | grep "Logged in as $LASTPASS_LOGIN" &> /dev/null
    then
        lpass login "${LASTPASS_LOGIN}"
    fi
    lpass show --notes ${LASTPASS_RSA_ID} > ~/.ssh/id_rsa
    chmod 600 ~/.ssh/id_rsa
    lpass show --notes ${LASTPASS_RSA_PUB_ID} > ~/.ssh/id_rsa.pub
    info "SSH keys extracted"
}

# install_package <package_name>
install_package() {
    package_name=$1
   if [ "${install_command}" = "" ] ; then
        error "No install command set"
    fi
    if [ "${package_name}" = "" ] ; then
        error "$0: no package name supplied"
    fi
    eval $install_command $package_name
}

# Main

determine_distro
set_distro_vars ${distro}

if ! command -v git &> /dev/null ; then
    error "git not installed"
fi

if ! command -v ssh &> /dev/null ; then
    error "ssh not installed"
fi

if ! is_ssh_keys_installed ; then
    info SSH-keys not installed, trying to extract with lastpass
    if ! which lpass &> /dev/null ; then
        if install_lastpass ; then
            extract_ssh_keys
        fi
    else
        extract_ssh_keys
    fi
else
    info SSH keys already installed
fi

if is_fish_installed ; then
    info "fish already installed"
else
    info "fish not installed, trying to install"
    install_package ${fish_package}
fi
