#!/bin/bash

# yadm/bootstrap -- ensure enough is installed to punt to bin/doctor

# info <message>
info() {
    echo "BOOTSTRAP: $*"
}

# error <message>
error() {
    echo "BOOTSTRAP-ERR: $*"
    exit 1
}

# try to figure out which distro we're on
determine_distro() {
    if [ -e /etc/arch-release ] ; then
        distro=arch
        return 0
    fi
   if [ -f  /etc/system-release ] ; then
       if egrep "CentOS|RHEL" /etc/system-release &> /dev/null ; then
             distro=rhel
             return 0
       fi
       if grep "Fedora" /etc/system-release &> /dev/null ; then
           distro=fedora
           return 0
       fi
   fi
   distro=unknown
   return 0
}

# set_distro_vars <distro>
set_distro_vars() {
    info "configuring vars for $1"
    case "$1" in
       arch)
         install_command="sudo pacman -S"
         query_command="pacman -Q"
         python_command="python"
         python_package="python"
         pip_command="pip"
         pip_package="python-pip"
         zsh_command="zsh"
         zsh_package="zsh"
         ;;
       centos)
           install_command="sudo dnf install -y"
           query_command="dnf list installed"
           python_command="python3"
           python_package="python39"
           pip_command="pip3"
           pip_package="python39-pip"
           zsh_command="zsh"
           zsh_package="zsh"
           ;;
       fedora)
           install_command="sudo dnf install -y"
           query_command="dnf list installed"
           python_command="python3"
           python_package="python3"
           pip_command="pip3"
           pip_package="python3-pip"
           zsh_command="zsh"
           zsh_package="zsh"
           ;;
       unknown)
           error "Unknown distro"
           ;;
       *)
           error "Distro has been determined, but variables for it not defined"
    esac
    info "continuing with following vars"
    info "  install_command=\"${install_command?install_command missing}\""
    info "  query_command=\"${query_command?query_command missing}\""
    info "  python_command=\"${python_command?python_command missing}\""
    info "  python_package=\"${python_package?python_package missing}\""
    info "  pip_command=\"${pip_command?pip_command missing}\""
    info "  pip_package=\"${pip_package?pip_package missing}\""
    info "  zsh_command=\"${zsh_command?zsh_command missing}\""
    info "  zsh_package=\"${zsh_package?zsh_package missing}\""
}

# install_package <package_name>
install_package() {
    package_name=$1
   if [ "${install_command}" = "" ] ; then
        error "No install command set"
    fi
    if [ "${package_name}" = "" ] ; then
        error "$0: no package name supplied"
    fi
    if ! eval $install_command $package_name ; then
        error "Couldn't install $package_name"
    fi
}

ensure_element_is_installed() {
    if [ "$1" = "" ] ; then
        error "no argument passed to ensure_element_is_installed"
    fi
    local element command_var command package_var package
    element="$1"
    info "checking if ${element} is installed"
    command_var=${element}_command
    command=${!command_var}
    package_var=${element}_package
    package=${!package_var}
    if command -v ${command} &> /dev/null ; then
        info "  yes"
        return 0
    else
        info "  no -- installing"
        install_package ${package}
    fi
}

# ensure_pip_module <module>
ensure_pip_module() {
    if ! ${python_command:?} -c "import $1" &> /dev/null ; then
        $pip_command install --user $1
    fi
}

determine_distro
set_distro_vars ${distro}

if ! command -v git &> /dev/null ; then
    error "git not installed"
fi

if ! command -v ssh &> /dev/null ; then
    error "ssh not installed"
fi

for elt in python pip zsh ; do
    ensure_element_is_installed $elt
done

for i in xdg voluptuous pyyaml ; do
  ensure_pip_module $i
done

info "submodule init"
~/bin/yadm submodule update --recursive --init

info "done, consider running ~/bin/doctor --configure --apply"
~/bin/doctor --configure --apply
