#!/bin/bash

# Get enough working that we can run doctor script

# info <message>
info() {
    echo "BOOTSTRAP: $*"
}

# error <message>
error() {
    echo "BOOTSTRAP-ERR: $*"
    exit 1
}

# try to figure out which distro we're on
determine_distro() {
    if [ -e /etc/arch-release ] ; then
        distro=arch
        return 0
    fi
   if [ -f  /etc/system-release ] ; then
       if grep "CentOS|RHEL" /etc/system-release &> /dev/null ; then
             distro=rhel
             return 0
       fi
       if grep "Fedora" /etc/system-release &> /dev/null ; then
           distro=fedora
           return 0
       fi
   fi
   distro=unknown
   return 0
}

# set_distro_vars <distro>
set_distro_vars() {
    case "$1" in
       arch)
         install_command="sudo pacman -S"
         query_command="pacman -Q"
         python_command="python"
         python_package="python"
         pip_command="pip"
         zsh_package="zsh"
         ;;
       centos)
           install_command="sudo dnf install -y"
           query_command="dnf list installed"
           python_command="python3"
           python_package="python39"
           pip_command="pip3"
           zsh_package="zsh"
           ;;
       fedora)
           install_command="sudo dnf install -y"
           query_command="dnf list installed"
           python_command="python3"
           python_package="python3"
           pip_command="pip3"
           zsh_package="zsh"
           ;;
       unknown)
           info "Unknown distro, will not be able to install packages"
           ;;
       *)
           error "Distro has been determined, but variables for it not defined"
    esac
}

# install_package <package_name>
install_package() {
    package_name=$1
   if [ "${install_command}" = "" ] ; then
        error "No install command set"
    fi
    if [ "${package_name}" = "" ] ; then
        error "$0: no package name supplied"
    fi
    if ! eval $install_command $package_name ; then
        error "Couldn't install $package_name"
    fi
}

is_python_installed() {
    info "checking if python is installed"
    if command -v python &> /dev/null ; then
        info "  yes"
        return 0
    else
        info "  no"
        return 1
    fi
}

is_zsh_installed() {
    info "checking if zsh is installed"
    if command -v zsh &> /dev/null ; then
        info "  yes"
        return 0
    else
        info "  no"
        return 1
    fi
}

# ensure_pip_module <module>
ensure_pip_module() {
    if ! ${python_command:?} -c "import $1" &> /dev/null ; then
        $pip_command install --user $1
    fi
}

determine_distro
set_distro_vars ${distro}

if ! command -v git &> /dev/null ; then
    error "git not installed"
fi

if ! command -v ssh &> /dev/null ; then
    error "ssh not installed"
fi

info "submodule init"
~/bin/yadm submodule update --recursive --init

if ! is_python_installed ; then
    info "Python not installed, rectifying"
    install_package python
fi

ensure_pip_module xdg

if ! is_zsh_installed ; then
    install_package zsh
fi

info "punting to doctor"
~/bin/doctor
